title: Keith Cheung # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="www.linkedin.com/in/keithcheung328">LinkedIn</a> 
  <br>
  <a href="file:///C:/Users/keith/Documents/Keith_Cheung_Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/Keith-Cheung/">GitHub</a>  
  
theme: jekyll-theme-minimal
