title: Keith Cheung # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="www.linkedin.com/in/keithcheung328">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/Keith-Cheung/">GitHub</a>  
  
theme: jekyll-theme-minimal
